/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package regalfinal;

import static java.lang.Integer.parseInt;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class batchfinal extends javax.swing.JFrame {

    page4 pg4;
    batchfinal(page4 p)
    {
        pg4=p;
        initComponents();
        Fillcmbcoursename();
    }
    public batchfinal() {
        initComponents();
        Fillcmbcoursename();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbcoursesend = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtduration = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtfees = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtfirsttimefrom = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtfirsttimeto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtsecondtimefrom = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtsecondtimeto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmessagesend = new javax.swing.JTextArea();
        btnemailsend = new javax.swing.JButton();
        btnbacksend = new javax.swing.JButton();
        cmbfirst = new javax.swing.JComboBox();
        cmbsecond = new javax.swing.JComboBox();
        dcdate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(668, 529));

        jPanel2.setBackground(new java.awt.Color(135, 130, 135));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Batch Info:");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/702018.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Course:");

        cmbcoursesend.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        cmbcoursesend.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " " }));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Start Date:");

        jLabel7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel7.setText("Duration:");

        txtduration.setBackground(new java.awt.Color(135, 130, 135));
        txtduration.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtduration.setForeground(new java.awt.Color(255, 255, 255));
        txtduration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdurationActionPerformed(evt);
            }
        });
        txtduration.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdurationKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Months");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setText("Fees:");

        txtfees.setBackground(new java.awt.Color(135, 130, 135));
        txtfees.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtfees.setForeground(new java.awt.Color(255, 255, 255));
        txtfees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfeesKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setText("First Shilt Timing:");

        txtfirsttimefrom.setBackground(new java.awt.Color(135, 130, 135));
        txtfirsttimefrom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtfirsttimefrom.setForeground(new java.awt.Color(255, 255, 255));
        txtfirsttimefrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirsttimefromKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("to");

        txtfirsttimeto.setBackground(new java.awt.Color(135, 130, 135));
        txtfirsttimeto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtfirsttimeto.setForeground(new java.awt.Color(255, 255, 255));
        txtfirsttimeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtfirsttimetoKeyTyped(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setText("Second Shift Timing:");

        txtsecondtimefrom.setBackground(new java.awt.Color(135, 130, 135));
        txtsecondtimefrom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtsecondtimefrom.setForeground(new java.awt.Color(255, 255, 255));
        txtsecondtimefrom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsecondtimefromKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText("to");

        txtsecondtimeto.setBackground(new java.awt.Color(135, 130, 135));
        txtsecondtimeto.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtsecondtimeto.setForeground(new java.awt.Color(255, 255, 255));
        txtsecondtimeto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtsecondtimetoKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel14.setText("Message:");

        txtmessagesend.setBackground(new java.awt.Color(135, 130, 135));
        txtmessagesend.setColumns(20);
        txtmessagesend.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txtmessagesend.setForeground(new java.awt.Color(255, 255, 255));
        txtmessagesend.setRows(5);
        txtmessagesend.setText("Good Luck\n");
        jScrollPane1.setViewportView(txtmessagesend);

        btnemailsend.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnemailsend.setText("Email");
        btnemailsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnemailsendActionPerformed(evt);
            }
        });

        btnbacksend.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnbacksend.setText("Back");
        btnbacksend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbacksendActionPerformed(evt);
            }
        });

        cmbfirst.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbfirst.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));
        cmbfirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbfirstActionPerformed(evt);
            }
        });

        cmbsecond.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbsecond.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ", "AM", "PM" }));

        dcdate.setBackground(new java.awt.Color(135, 130, 135));
        dcdate.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtsecondtimefrom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtsecondtimeto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbsecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtfirsttimefrom, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtfirsttimeto, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(cmbfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 29, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(btnemailsend, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnbacksend, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel8))
                                            .addComponent(dcdate, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbcoursesend, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(39, 39, 39)
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(txtfees, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 122, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcoursesend, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(dcdate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtduration, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(txtfees, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfirsttimeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtfirsttimefrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cmbfirst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsecondtimefrom, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsecondtimeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(cmbsecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnemailsend, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbacksend, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbacksendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbacksendActionPerformed
        pg4.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_btnbacksendActionPerformed

    private void cmbfirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbfirstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbfirstActionPerformed

    private void txtdurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdurationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdurationActionPerformed

    private void txtdurationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdurationKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==true)
            evt.consume();
    }//GEN-LAST:event_txtdurationKeyTyped

    private void txtfeesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfeesKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==true)
            evt.consume();
    }//GEN-LAST:event_txtfeesKeyTyped

    private void txtfirsttimefromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirsttimefromKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==true)
            evt.consume();
    }//GEN-LAST:event_txtfirsttimefromKeyTyped

    private void txtfirsttimetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtfirsttimetoKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==true)
            evt.consume();
    }//GEN-LAST:event_txtfirsttimetoKeyTyped

    private void txtsecondtimefromKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecondtimefromKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==true)
            evt.consume();
    }//GEN-LAST:event_txtsecondtimefromKeyTyped

    private void txtsecondtimetoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsecondtimetoKeyTyped
        char ch;
        ch=evt.getKeyChar();
        if(Character.isAlphabetic(ch)==true)
            evt.consume();
    }//GEN-LAST:event_txtsecondtimetoKeyTyped

    private void btnemailsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnemailsendActionPerformed
        if(parseInt(txtfirsttimefrom.getText())>13 || parseInt(txtfirsttimeto.getText())>13)
        {
            txtfirsttimefrom.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Please check timming");
        }
        else if(parseInt(txtsecondtimefrom.getText())>13 || parseInt(txtsecondtimeto.getText())>13)
        {
            txtsecondtimefrom.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Please check timming");
        }
        else if(cmbcoursesend.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "Please select course");
        }
        else if(dcdate.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "Please select date");
        }
        else if(txtduration.getText().equals(""))
        {
            txtduration.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Please enter duration");
        }
        else if(txtfees.getText().equals(""))
        {
             txtfees.requestFocusInWindow();
            JOptionPane.showMessageDialog(null, "Please enter fees");
        }
        else if(cmbfirst.getSelectedIndex()==0 || cmbsecond.getSelectedIndex()==0)
        {
            JOptionPane.showMessageDialog(null, "Please select AM/PM");
        }
        else
        {
            int x,i;
            try {
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enquiryformtest", "root", "root");
                Statement st=con.createStatement();        
                   ResultSet rs1=st.executeQuery("select * from mainform");
                   while(rs1.next()){     
                        String to = rs1.getString("mail");
                        String subject = String.valueOf("Regal Classes:- "+cmbcoursesend.getSelectedItem()+" course");
                        String message =  String.valueOf("Start Date:\t"+dcdate.getDate()+"\n\nDuration:\t"+txtduration.getText()+" months\n\nFees:\t"+txtfees.getText()+" Rs\n\nFirst Shift Timming:\t"+txtfirsttimefrom.getText()+" to "+txtfirsttimeto.getText()+" "+cmbfirst.getSelectedItem()+"\n\nSecond Shift Timming:\t"+txtsecondtimefrom.getText()+" to "+txtsecondtimeto.getText()+" "+cmbsecond.getSelectedItem()+"\n\nMessage: "+txtmessagesend.getText());
                        String user = "tejasbadmore001@gmail.com";
                        String pass = "tejasbadmore001";
                        SendMail.send(to,subject, message, user, pass);
                    }
                
            } catch (SQLException ex) {
               // JOptionPane.showMessageDialog(null, "error");
               Logger.getLogger(batchfinal.class.getName()).log(Level.SEVERE, null, ex);
            }
                       
        }
    }//GEN-LAST:event_btnemailsendActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        this.setState(1);
    }//GEN-LAST:event_jLabel4MousePressed

    private void Fillcmbcoursename()
    {
        try
        {
            Connection con;
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/enquiryformtest","root","root");
            String sql1="select coursename from course";
            Statement st=con.createStatement();
            ResultSet rs= st.executeQuery(sql1);
            while(rs.next())
            {
                String name=rs.getString("coursename");
                cmbcoursesend.addItem(name);
            }
            
        }
        catch(SQLException e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(batchfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(batchfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(batchfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(batchfinal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new batchfinal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnbacksend;
    private javax.swing.JButton btnemailsend;
    private javax.swing.JComboBox cmbcoursesend;
    private javax.swing.JComboBox cmbfirst;
    private javax.swing.JComboBox cmbsecond;
    private com.toedter.calendar.JDateChooser dcdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtduration;
    private javax.swing.JTextField txtfees;
    private javax.swing.JTextField txtfirsttimefrom;
    private javax.swing.JTextField txtfirsttimeto;
    private javax.swing.JTextArea txtmessagesend;
    private javax.swing.JTextField txtsecondtimefrom;
    private javax.swing.JTextField txtsecondtimeto;
    // End of variables declaration//GEN-END:variables
}
